apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service-workshop
spec:
  selector:
    matchLabels:
      app: simple-service
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
      - name: simple-container
        image: gcr.io/pontoporponto/simple-service:latest
        resources:
          limits:
            memory: 50M